# Generated by Django 3.0 on 2022-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb', models.CharField(choices=[('De', 'None'), ('Py', 'Python'), ('Jv', 'Java')], default='De', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=150)),
            ],
        ),
    ]
